function C_A_New = Diffusion_A(C_A,T)

Sx=size(x,1);

a=1:Sx;b=(1:Sx)';
A=repmat(a,Sx,1);B=repmat(b,1,Sx);
A=A(:);B=B(:);
K=[A B];U=randperm(size(A,1));
K=K(U,:);

T=repmat(T,Sx,Sx);
fD=@(D0,Q,T)D0(exp(-Q/(R*T)));
D=arrayfun(fD,D0,Q,T);

for i=Sx/2+1:Sx-1
    for n=1:Sx^2
        j=K(n,1);
        k=K(n,2);
        if j==1
            C_A(i,j,k)=(D(i,j,k)*C_A(i,j,k)+Dt/Dx*(...
            D(i-1,j,k)*(C_A(i-1,j,k)-C_A(i,j,k))+...
            D(i+1,j,k)*(C_A(i+1,j,k)-C_A(i,j,k))+...
            D(i,j+1,k)*(C_A(i,j+1,k)-C_A(i,j,k))+...
            D(i,Sx,k)*(C_A(i,Sx,k)-C_A(i,j,k))+...
            D(i,j,k+1)*(C_A(i,j,k+1)-C_A(i,j,k))+...
            D(i,j,k-1)*(C_A(i,j,k-1)-C_A(i,j,k))))/D(i,j,k);
        elseif j==Sx
            C_A(i,j,k)=(D(i,j,k)*C_A(i,j,k)+Dt/Dx*(...
            D(i-1,j,k)*(C_A(i-1,j,k)-C_A(i,j,k))+...
            D(i+1,j,k)*(C_A(i+1,j,k)-C_A(i,j,k))+...
            D(i,1,k)*(C_A(i,1,k)-C_A(i,j,k))+...
            D(i,j-1,k)*(C_A(i,j-1,k)-C_A(i,j,k))+...
            D(i,j,k+1)*(C_A(i,j,k+1)-C_A(i,j,k))+...
            D(i,j,k-1)*(C_A(i,j,k-1)-C_A(i,j,k))))/D(i,j,k);
        elseif k==1
            C_A(i,j,k)=(D(i,j,k)*C_A(i,j,k)+Dt/Dx*(...
            D(i-1,j,k)*(C_A(i-1,j,k)-C_A(i,j,k))+...
            D(i+1,j,k)*(C_A(i+1,j,k)-C_A(i,j,k))+...
            D(i,j+1,k)*(C_A(i,j+1,k)-C_A(i,j,k))+...
            D(i,j-1,k)*(C_A(i,j-1,k)-C_A(i,j,k))+...
            D(i,j,k+1)*(C_A(i,j,k+1)-C_A(i,j,k))+...
            D(i,j,Sx)*(C_A(i,j,Sx)-C_A(i,j,k))))/D(i,j,k);
        elseif k==Sx
            C_A(i,j,k)=(D(i,j,k)*C_A(i,j,k)+Dt/Dx*(...
            D(i-1,j,k)*(C_A(i-1,j,k)-C_A(i,j,k))+...
            D(i+1,j,k)*(C_A(i+1,j,k)-C_A(i,j,k))+...
            D(i,j+1,k)*(C_A(i,j+1,k)-C_A(i,j,k))+...
            D(i,j-1,k)*(C_A(i,j-1,k)-C_A(i,j,k))+...
            D(i,j,1)*(C_A(i,j,1)-C_A(i,j,k))+...
            D(i,j,k-1)*(C_A(i,j,k-1)-C_A(i,j,k))))/D(i,j,k);
            
        else
            C_A(i,j,k)=(D(i,j,k)*C_A(i,j,k)+Dt/Dx*(...
            D(i-1,j,k)*(C_A(i-1,j,k)-C_A(i,j,k))+...
            D(i+1,j,k)*(C_A(i+1,j,k)-C_A(i,j,k))+...
            D(i,j+1,k)*(C_A(i,j+1,k)-C_A(i,j,k))+...
            D(i,j-1,k)*(C_A(i,j-1,k)-C_A(i,j,k))+...
            D(i,j,k+1)*(C_A(i,j,k+1)-C_A(i,j,k))+...
            D(i,j,k-1)*(C_A(i,j,k-1)-C_A(i,j,k))))/D(i,j,k);
        end
    end
end
C_A_New=C_A;
    